version: '3'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=symfony
            - MYSQL_USER=root
    web:
        build: .
        ports:
            - 8080:80
        volumes:
            - .:/var/www/