version: '3.7'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: root